In [ ]:
import pytorch as torch

ModuleNotFoundError: No module named 'pytorch'

In [ ]:
!import pytorch as torch

/bin/bash: line 1: import: command not found


In [ ]:
!pip install pytorch

  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pytorch)


In [ ]:
!pip install torch

In [ ]:
import torch as torch
torch.__version__


'2.8.0+cu126'

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.intem()

AttributeError: 'Tensor' object has no attribute 'intem'

In [ ]:
scalar.item()

7

In [ ]:
scalar

tensor(7)

In [ ]:
vector = torch.tensor([3,2,4])

In [ ]:
vector

tensor([3, 2, 4])

In [ ]:
vector.shape()

TypeError: 'torch.Size' object is not callable

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
vector.ndim

1

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix.ndim

NameError: name 'Matrix' is not defined

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor , random_tensor.dtype

(tensor([[0.8102, 0.8579, 0.5683, 0.9805],
         [0.9503, 0.7923, 0.1110, 0.0768],
         [0.2090, 0.4056, 0.7356, 0.1595]]),
 torch.float32)

In [ ]:
random_tensor.item()

RuntimeError: a Tensor with 12 elements cannot be converted to Scalar

In [ ]:
random_tensor.item

<function Tensor.item>

In [ ]:
random_tensor[0][0].item

<function Tensor.item>

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
tensor = torch.tensor([[1, 2, 3] , [4,5,6]])
t = torch.mm(tensor, tensor.T)
torch.mm(t , t.T)

tensor([[1220, 2912],
        [2912, 6953]])

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
x = torch.arange(0 , 100 , 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print("mean:" , x.type(torch.float64).mean())

mean: tensor(45., dtype=torch.float64)


In [ ]:
print("max:" , x.max())
print("min" , x.min())
print("sum:" , x.sum())

max: tensor(90)
min tensor(0)
sum: tensor(450)


In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)


(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
print(f"Index of the max: {torch.argmax(x)}")
print(f"Index of the min:{torch.argmin(x)}")

Index of the max: 9
Index of the min:0


In [ ]:
tensor , tensor.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [ ]:
tensor_reshaped = tensor.reshape(3,2)

In [ ]:
tensor_reshaped

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor_view = tensor_reshaped.view(1,6)

In [ ]:
tensor_view

tensor([[1, 2, 3, 4, 5, 6]])

In [ ]:
tensor_reshaped

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor_view[0] = 0
tensor_reshaped

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [ ]:
tensor_view = torch.ones_like(tensor_reshaped)


In [ ]:
tensor_view


tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [ ]:
tensor_reshaped

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [ ]:
tensor_view += 1

In [ ]:
tensor_view

tensor([[2, 2],
        [2, 2],
        [2, 2]])

In [ ]:
tensor_reshaped

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [ ]:
tensor_stack = torch.stack([tensor, tensor, tensor], dim=2)

In [ ]:
tensor_stack

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [ ]:
tensor

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
x_squez = tensor_stack.squeeze()

In [ ]:
x_squez

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
